#!/bin/tcsh -f

# ------------------------------
# Process command line arguments
# ------------------------------

if ($#argv != 4) then
   goto usage
endif

while ($#argv)

   if ( ( "$1" != "-levs" ) && ( "$1" != "-outdir") ) then
      goto usage
   endif

   if ("$1" == "-levs") then
      shift; if (! $#argv) goto usage
      set numlevs = $1
   endif

   if ("$1" == "-outdir") then
      shift; if (! $#argv) goto usage
      set outdir = "$1"
   endif

   shift
end

echo "Remapping to $numlevs levels"
echo "Output will be saved to $outdir"

# ----------------
# Test for BINDIR
# ----------------

if ( $?BINDIR ) then
   if ( $BINDIR == '' ) then
      echo "Error: BINDIR is set to blank. Please set it correctly"
      exit 1
   else 
      echo "BINDIR: $BINDIR"
   endif
else
   echo "Error: BINDIR must be set"
   exit 1
endif

# ---------------------------------
# Test for required files in BINDIR
# ---------------------------------

if ( -e $BINDIR/g5_modules ) then
   source $BINDIR/g5_modules
else
   echo "Error: g5_modules not found in $BINDIR"
   exit 1
endif

if ( ! -x $BINDIR/GFIO_remap.x ) then
   echo "Error: GFIO_remap.x not found in $BINDIR"
   exit 1
endif

set indir = "/discover/nobackup/projects/gmao/share/dasilva/fvInput/fvInput_nc3/CMIP/L72"

mkdir -p $outdir

cd $outdir

# -----------------------------------
# Copy input ps_delp files for safety
# -----------------------------------

set RES_TYPES = ( x288_y181 x144_y091 )

set input_psdir = $outdir/inputps
mkdir -p $input_psdir

set archdir = "/archive/u/mathomp4/Merra2_PSDELP_forRemap/PerMonth"

foreach RES ( `echo $RES_TYPES` )

   foreach month ( `seq -w 01 12` )

      if ( ! -f $input_psdir/merra2.aer_Nv.ps_delp.$RES.2003-2014.2008${month}clm.nc4 ) then
         cp -v $archdir/merra2.aer_Nv.ps_delp.$RES.2003-2014.2008${month}clm.nc4 $input_psdir
      endif
   end
end

set TYPE_TABLE = ( cmip5.aircraft_fuel gmi_oh_ch4_h2o2_no3 )

foreach TYPE ( `echo $TYPE_TABLE` ) 

   echo "Running $TYPE..."
   
   if ( $TYPE == "cmip5.aircraft_fuel" ) then
      set PS_FILE = "$input_psdir/merra2.aer_Nv.ps_delp.x288_y181.2003-2014.2008"
      set TAGO = "x288_y181_z${numlevs}_t14"
   else if ( $TYPE == "gmi_oh_ch4_h2o2_no3"  ) then
      set PS_FILE = "$input_psdir/merra2.aer_Nv.ps_delp.x144_y091.2003-2014.2008"
      set TAGO = "x144_y91_z${numlevs}_t12"
   endif

   foreach IFILE ( `find $indir -type f -iname "${TYPE}*"` )
      set FILE = `basename $IFILE`
      set TAG1 = `echo $FILE | awk -F. '{print $1 }'`
      set TAG2 = `echo $FILE | awk -F. '{print $2 }'`
      set TAG3 = `echo $FILE | awk -F. '{print $3 }'`
      set TAG4 = `echo $FILE | awk -F. '{print $4 }'`
      set TAG5 = `echo $FILE | awk -F. '{print $5 }'`
      set TAG6 = `echo $FILE | awk -F. '{print $6 }'`
      set TAG7 = `echo $FILE | awk -F. '{print $7 }'`

      if ( $TAG4 == "nc" || $TAG4 == "nc4" ) then
         set ix = 4
         @ ix1 = $ix - 1
         set TAG = $TAG3
         set NC_TAG = $TAG4
         echo  $FILE $TAG1 $TAG 
      endif

      if ( $TAG5 == "nc" || $TAG5 == "nc4" ) then
         set ix = 5
         @ ix1 = $ix - 1
         set NC_TAG = $TAG5
         set TAG = $TAG4
         echo  $FILE $TAG1 $TAG 
      endif
      if ( $TAG6 == "nc" || $TAG6 == "nc4" ) then
         set ix = 6
         @ ix1 = $ix - 1
         set NC_TAG = $TAG6
         set TAG = $TAG5
         echo  $FILE $TAG1 $TAG 
      endif
      if ( $TAG7 == "nc" || $TAG7 == "nc4" ) then
         set ix = 7
         @ ix1 = $ix - 1
         set NC_TAG = $TAG7
         set TAG = $TAG6
         echo $FILE $TAG1 $TAG 
      endif


      if ( $TYPE == "cmip5.aircraft_fuel" ) then
         
         #  cmip5.aircraft_fuel
         
         $BINDIR/GFIO_remap.x -shift  -pref 100000 -o ${FILE}.LON_0_360 \
                                                      ${indir}/$FILE 
         mv ${FILE}.LON_0_360 $FILE

         $BINDIR/GFIO_remap.x -nlev ${numlevs} -like_sph 1,fuel -pref 100000 -psfile $PS_FILE -clim -add_delp  \
                                                         -o $TYPE.eta.${TAGO}.$TAG.$NC_TAG.LON_0_360 \
                                                            ${FILE}

         $BINDIR/GFIO_remap.x -shift  -pref 100000 -o ${outdir}/$TYPE.eta.${TAGO}.${TAG}.$NC_TAG \
                                                      $TYPE.eta.${TAGO}.${TAG}.${NC_TAG}.LON_0_360

         /bin/rm $FILE
         /bin/rm $TYPE.eta.${TAGO}.${TAG}.${NC_TAG}.LON_0_360

      else if ( $TYPE == "gmi_oh_ch4_h2o2_no3"  ) then

         # $BINDIR/GFIO_remap.x -shift  -pref 100000 -o ${FILE}.LON_0_360 ${indir}/$FILE 
         # mv ${FILE}.LON_0_360 $FILE

         # $BINDIR/GFIO_remap.x -nlev ${numlevs} -pref 100000 -like_sph 4,oh,ch4,h2o2,no3 \
         #                                                 -o $TYPE.eta.${TAGO}.${TAG}.${NC_TAG}.LON_0_360 \
         #                                                    $indir/$FILE

         # $BINDIR/GFIO_remap.x -shift  -pref 100000 -o ${outdir}/$TYPE.eta.${TAGO}.${TAG}.$NC_TAG \
         #                                               $TYPE.eta.${TAGO}.${TAG}.${NC_TAG}.LON_0_360

         # /bin/rm  gmi_oh_ch4_h2o2_no3.${TAGO}.${TAG}.${NC_TAG}.LON_0_360

         $BINDIR/GFIO_remap.x -nlev ${numlevs} -pref 100000 -like_sph 4,oh,ch4,h2o2,no3 \
                                                         -o ${outdir}/$TYPE.eta.${TAGO}.${TAG}.${NC_TAG} \
                                                            $indir/$FILE
      endif
   end
end

usage:
cat <<EOF

usage: $0:t -levs numlevels -outdir OUTDIR

EOF
