#!/bin/tcsh -f

# ------------------------------
# Process command line arguments
# ------------------------------

if ($#argv != 4) then
   goto usage
endif

while ($#argv)

   if ( ( "$1" != "-levs" ) && ( "$1" != "-outdir") ) then
      goto usage
   endif

   if ("$1" == "-levs") then
      shift; if (! $#argv) goto usage
      set numlevs = $1
   endif

   if ("$1" == "-outdir") then
      shift; if (! $#argv) goto usage
      set outdir = "$1"
   endif

   shift
end

echo "Remapping to $numlevs levels"
echo "Output will be saved to $outdir"

# ----------------
# Test for BINDIR
# ----------------

if ( $?BINDIR ) then
   if ( $BINDIR == '' ) then
      echo "Error: BINDIR is set to blank. Please set it correctly"
      exit 1
   else 
      echo "BINDIR: $BINDIR"
   endif
else
   echo "Error: BINDIR must be set"
   exit 1
endif

# ---------------------------------
# Test for required files in BINDIR
# ---------------------------------

if ( -e $BINDIR/g5_modules ) then
   source $BINDIR/g5_modules
else
   echo "Error: g5_modules not found in $BINDIR"
   exit 1
endif

if ( ! -x $BINDIR/convert_aerosols.x ) then
   echo "Error: convert_aerosols.x not found in $BINDIR"
   exit 1
endif

set SHAREL72DIR = /discover/nobackup/projects/gmao/share/dao_ops/fvInput_nc3/g5chem/L72/aero_clm

# MAT: Note that convert_aerosols.x should be compiled at r8 for this task. Some
#      of the aerosols climatology values are very small and instabilities can be
#      seen at r4
#      You'll need to compile *all* of post as r8 for this to work. I tried to make
#      some GNU make fanciness do it, did not take.


cd $SHAREL72DIR

set files = `ls -1 gfed*.nc`

mkdir -p $outdir

cd $outdir

# -----------------------------------
# Copy input ps_delp files for safety
# -----------------------------------

set input_psdir = $outdir/inputps
mkdir -p $input_psdir

set archdir = "/archive/u/mathomp4/Merra2_PSDELP_forRemap/"

if ( ! -f $input_psdir/merra2.aer_Nv.ps_delp.x288_y181.2003-2014.2008clm.nc4 ) then
   cp -v $archdir/merra2.aer_Nv.ps_delp.x288_y181.2003-2014.2008clm.nc4 $input_psdir
endif

foreach file ($files)

   ln -s $SHAREL72DIR/$file fdummy
   $BINDIR/convert_aerosols.x -psfile $input_psdir/merra2.aer_Nv.ps_delp.x288_y181.2003-2014.2008clm.nc4 -f fdummy -lm ${numlevs}
   /bin/rm fdummy
   /bin/mv fdummy* $file

   if(-e filename1 ) /bin/rm filename1
   if(-e filename2 ) /bin/rm filename2
   echo $file                                  > filename1
   echo $file |  sed -e "s/z72/z${numlevs}/g"  > filename2

   # Only do this (useless?) move if the names are different
   # This mainly avoids an annoying warning from mv
   if (`cat filename1` != `cat filename2`) then
      /bin/mv `cat filename1 filename2`
   endif

end

if(-e filename1 ) /bin/rm filename1
if(-e filename2 ) /bin/rm filename2

usage:
cat <<EOF

usage: $0:t -levs numlevels -outdir OUTDIR

EOF
